security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  password_hashers:
    App\Entity\User: 'auto'

  firewalls:
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        always_use_default_target_path: true
        default_target_path: /
        username_parameter: _username
        password_parameter: _password
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 172800   # 2 jours
        path: /
      logout:
        path: app_logout
        target: /

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
